### ISSUE TITLE
Documentation epic

### ISSUE THREAD

**Issue by abmantz** [KIPAC/StatisticalMethods#106]
Let's separate these tasks from the lecture notes issue(s). We need to fix/update

- [x] Homework guidelines (#93)
- [x] Project guidelines (#105)
- [x] Getting started page
  - [x] List of python packages (#91) - see also the travis issue, #78
  - [x] AOB
- [x] Unwatching of repos (#82) (Not sure whether this goes in GettingStarted or Stanford now...)
- [x] Stanford unix farm Getting Started (#79)
- [x] Document existence of Slack group in Stanford.md (#92)
- [x] Schedule.md does not exist, and should be called something else: replace `lessons/index.ipynb` with `chunks/README.md`
- [x] Update top-level README
- [x] Update gh-pages (automatically?)
- [x] Add a list of MCMC packages (separate from GettingStarted)
- [x] Either make binder work or remove it from the front page (#74)
- [x] Move or delete unused stuff from last year

- [x] Check that everything is in order

**Comment by drphilmarshall** [comment]
I put the schedule/index for the course in the top level folder: 

https://github.com/KIPAC/StatisticalMethods/blob/2017/index.ipynb

It's pretty simple right now - just a list of links to the various chunks, in the order given in the planning doc. The `chunks` folder has no README, but could perhaps be given a simple one just explaining what these notebooks are. `gh-pages` is up to date, I'll work on the `requirements.txt` now.

**Comment by abmantz** [comment]
Not to make waves, but I don't see why we need a separate Textbooks.md document at this point

**Comment by drphilmarshall** [comment]
Me neither - the old top level README file referred to one but I agree we
can do without it.

**Comment by drphilmarshall** [comment]
OK, I think we are in good shape, docs-wise. Closing out - the merge of #116 should give us a well navigable repo.
