### ISSUE TITLE
Start examples and exercises

### ISSUE THREAD

**Issue by drphilmarshall** [KIPAC/StatisticalMethods#6]
One folder per example dataset, and make stubs of notebooks based on existing material.
- [ ] examples/StraightLine (see #8 and #11 )
- [x] examples/XrayImage (see #9
- [x] examples/SDSScatalog (see #10)

**Comment by drphilmarshall** [comment]
Closing this, as only #8 and #11 remain and there's no need for an umbrella issue to hang around.
