### ISSUE TITLE
Redesign course and lessons

### ISSUE THREAD

**Issue by drphilmarshall** [KIPAC/StatisticalMethods#84]
Let's take our lesson plan from 2015, copy and then edit it so we have a plan we are both happy with looks the way we want it to for 2017. We can use this epic issue to track sub-issues relating to this redesign.

- [x] Chunk: intro to the course (#87)
- [x] Chunk: minimal tour of inference (#88)
- [x] Chunk: review of probability (#94)
- [x] Chunk: generative models (models I) (#89)
- [x] Chunk: Bayes theorem (#90)
- [ ] Chunk: straight line/philosophy (#95)
- [x] Chunk: sampling I (#96)
- [x] Chunk: sampling II (#97)
- [x] Chunk: models II (#98)
- [ ] Chunk: model evaluation and comparison (#99)
- [x] Chunk: "model-free" models (models III) (#100)
- [x] Chunk: sampling III (#112)
- [ ] Chunk: machine learning (#101)
- [ ] Chunk: models IV (coping) (#102)
- [ ] Chunk: fishing (#103)
- [ ] Chunk: non-sampling methods (#104)

**Comment by abmantz** [comment]
Assigning myself to get started with lesson 1 in a private document.

**Comment by abmantz** [comment]
Some organization is happening off-repo. Regardless, let's keep a to do list here linking to discrete things that need doing (i.e. no longer "proposed"). See the top comment!

**Comment by abmantz** [comment]
Closing this seeing how we have a plan and a load of individual issues
